### ISSUE TITLE
Issue #04 - Sample State

### ISSUE THREAD

**Issue by keginzburg** [joe-delaney/slack-chat#4]
# Sample State
- [X] State shape is flat!
- [X] State’s keys are camelCased
- [X] All keys within the values in the state are accessible in the schema
- [X] Correctly formatted
  - [X] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [X] Top level slices
    - [X] `entities`
    - [X] `session`
    - [X] `errors` (here or in `ui`)
    - [X] `ui` (if needed)
  - [X] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can’t change
    + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
Not a big deal, but I’d maybe add some variation to your sample state’s subscriptions and messages, so their respective polymorphic association data reflects Groups as well.

**Comment by joe-delaney** [comment]
Since slack only has one message feed visible at a time, I was thinking that the messages and subscriptions in state at any time would be the ones for the currently selected channel or group. When a user selects a different channel or group, I was thinking I would dispatch an action that updates those slices of state to fetch the relevant data from the backend.

Let me know if this is a good approach and if not, I can change my state to hold more information.

**Comment by keginzburg** [comment]
Gotcha. Honestly can't speak as to whether it's a good or bad approach, but definitely worth a try! Excited to see you experiment if necessary.
